/**
 * generated by Xtext
 */
package xtext.scoping.adventures.validation;

import xtext.scoping.adventures.validation.AbstractXscope1Validator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class Xscope1Validator extends AbstractXscope1Validator {
}
