/*
* generated by Xtext
*/
package xtext.scoping.adventures.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Xscope1AntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("xtext/scoping/adventures/parser/antlr/internal/InternalXscope1.tokens");
	}
}
