/*
* generated by Xtext
*/
package xtext.scoping.adventures.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.scoping.adventures.services.Xscope1GrammarAccess;

public class Xscope1Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Xscope1GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected xtext.scoping.adventures.parser.antlr.internal.InternalXscope1Parser createParser(XtextTokenStream stream) {
		return new xtext.scoping.adventures.parser.antlr.internal.InternalXscope1Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public Xscope1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Xscope1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
