/**
 * generated by Xtext
 */
package xtext.scoping.adventures.ui.contentassist;

import xtext.scoping.adventures.ui.contentassist.AbstractXscope1ProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class Xscope1ProposalProvider extends AbstractXscope1ProposalProvider {
}
