/*
 * generated by Xtext
 */
package xtext.scoping.adventures.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Xscope1UiModule extends xtext.scoping.adventures.ui.AbstractXscope1UiModule {
	public Xscope1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
