/*
* generated by Xtext
*/
package xtext.scoping.adventures;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Xscope1StandaloneSetup extends Xscope1StandaloneSetupGenerated{

	public static void doSetup() {
		new Xscope1StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

