/*
 * generated by Xtext
 */
package xtext.scoping.adventures;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Xscope1RuntimeModule extends xtext.scoping.adventures.AbstractXscope1RuntimeModule {

}
